[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.25.1"
# A URL to use to install `cargo-dist` (with the installer script)
cargo-dist-url-override = "https://dl.bearcove.cloud/dump/dist-cross"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "aarch64-pc-windows-msvc", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "aarch64-pc-windows-msvc"]

[dist.github-custom-runners.aarch64-linux-gnu]
runner = "ubuntu-20.04"
container = { image = "quay.io/pypa/manylinux_2_28_x86_64", host = "aarch64-unknown-linux-gnu" }

[dist.github-custom-runners.aarch64-pc-windows-msvc]
runner = "ubuntu-20.04"
container = { image = "messense/cargo-xwin", host = "x86_64-unknown-linux-gnu" }
