on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            container_image: quay.io/pypa/manylinux_2_28_x86_64
            install_rustup: true
          - target: aarch64-unknown-linux-gnu,aarch64-unknown-linux-gnu
            container_image: quay.io/pypa/manylinux_2_28_aarch64
            install_rustup: true
          - target: x86_64-pc-windows-msvc,aarch64-pc-windows-msvc
            container_image: messense/cargo-xwin
          - target: x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu
            runs-on: ubuntu-latest
            install_cargo_zigbuild: true
    runs-on: ${{ matrix.runs-on || 'ubuntu-latest' }}
    container: ${{ matrix.container_image || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        if: ${{ matrix.install_rustup }}
      - name: Install cargo-zigbuild
        if: ${{ matrix.install_cargo_zigbuild }}
        shell: bash
        run: pip install cargo-zigbuild
      - name: Install cargo-dist
        shell: bash
        run: "curl --proto '=https' --tlsv1.2 -LsSf https://dl.bearcove.cloud/dump/dist-cross/cargo-dist-installer.sh | sh"
      - name: Build local artifacts
        run: cargo dist build --artifacts local --target ${{ matrix.target }}
